### ISSUE TITLE
Scrollbar for Extensions tab

### ISSUE THREAD

**Issue by bataneske** [arcnations-united/evolve#3]
I've riced my shell to the point where the number of extensions surpasses the amount of screen space on my machine. **You can neither scroll using a mouse, touchpad nor Down arrow/Page down.**

The cutoff is clear when you compare the maximized and standard windows:

![Screenshot from 2024-05-22 20-34-40](https://github.com/arcnations-united/evolve/assets/107265248/3c866587-20e3-42b3-bfb7-24a7112eef84)

![Screenshot from 2024-05-22 20-30-49](https://github.com/arcnations-united/evolve/assets/107265248/4b9303cf-a7b7-4fba-b454-1e5b0988b076)

Another QOL feature related to Extensions tab I'd love to see in the next version is Escape button acting as the top left back button in the Install New and View Extension sections.

**Comment by arcnations-united** [comment]
Added support for scrolling in Extensions page. The escape button and other shortcuts will be added too soon. Not just on the Extensions page but everywhere else.
