### ISSUE TITLE
Make a backup of gtk-4 default theme

### ISSUE THREAD

**Issue by Ikytsu** [arcnations-united/evolve#6]
In case the theme is broken, you should put a default gtk-4 theme to help, or at least a button who do it.

i say that bcs it happened to me so i typed:
rm -rf ~/.config/gtk-4.0
dconf reset -f /org/gnome/desktop/interface/

**Comment by arcnations-united** [comment]
There's the adwaita global theme which resets all parameters of "gtk themes" to default including gtk-4
